# Generated by Django 5.0.4 on 2024-04-03 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_owner', models.CharField(max_length=20)),
                ('electronic_items', models.CharField(max_length=10)),
                ('item_price', models.CharField(max_length=10)),
                ('shop_address', models.CharField(max_length=20)),
                ('customer_name', models.CharField(max_length=20)),
                ('customer_mobile_no', models.IntegerField()),
                ('shop_opening_date', models.DateField()),
            ],
        ),
    ]
